apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: web-uat-
namespace: web-uat
resources:
  - ../../base
patches:
  - path: patch-deploy.yaml
images:
  - name: nhutlm1/react-nginx-lab
    newName: nhutlm1/react-nginx-lab
    newTag: 1.0.0
